# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hotel_tag.proto',
  package='protobuf.socketrpc',
  serialized_pb=_b('\n\x0fhotel_tag.proto\x12\x12protobuf.socketrpc\"\'\n\rhotel_request\x12\x16\n\x04name\x18\x01 \x02(\t:\x08Zo rooms\"\x8e\x01\n\x05hotel\x12\x16\n\x02hn\x18\x14 \x02(\t:\nTaj Hotel \x12\x1b\n\x10restaurant_count\x18\t \x02(\x05:\x01\x31\x12\x16\n\x08minprice\x18\r \x02(\x05:\x04\x32\x30\x30\x30\x12%\n\thotel_url\x18\x0f \x02(\t:\x12http://www.taj.com\x12\x11\n\x06rating\x18\x11 \x02(\x05:\x01\x32\x32\x61\n\x0cHotelService\x12Q\n\x11get_hotel_details\x12!.protobuf.socketrpc.hotel_request\x1a\x19.protobuf.socketrpc.hotelB\x06\x88\x01\x01\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HOTEL_REQUEST = _descriptor.Descriptor(
  name='hotel_request',
  full_name='protobuf.socketrpc.hotel_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.socketrpc.hotel_request.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("Zo rooms").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=78,
)


_HOTEL = _descriptor.Descriptor(
  name='hotel',
  full_name='protobuf.socketrpc.hotel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hn', full_name='protobuf.socketrpc.hotel.hn', index=0,
      number=20, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("Taj Hotel ").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restaurant_count', full_name='protobuf.socketrpc.hotel.restaurant_count', index=1,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minprice', full_name='protobuf.socketrpc.hotel.minprice', index=2,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hotel_url', full_name='protobuf.socketrpc.hotel.hotel_url', index=3,
      number=15, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("http://www.taj.com").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='protobuf.socketrpc.hotel.rating', index=4,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=223,
)

DESCRIPTOR.message_types_by_name['hotel_request'] = _HOTEL_REQUEST
DESCRIPTOR.message_types_by_name['hotel'] = _HOTEL

hotel_request = _reflection.GeneratedProtocolMessageType('hotel_request', (_message.Message,), dict(
  DESCRIPTOR = _HOTEL_REQUEST,
  __module__ = 'hotel_tag_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.hotel_request)
  ))
_sym_db.RegisterMessage(hotel_request)

hotel = _reflection.GeneratedProtocolMessageType('hotel', (_message.Message,), dict(
  DESCRIPTOR = _HOTEL,
  __module__ = 'hotel_tag_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.hotel)
  ))
_sym_db.RegisterMessage(hotel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\210\001\001\220\001\001'))

_HOTELSERVICE = _descriptor.ServiceDescriptor(
  name='HotelService',
  full_name='protobuf.socketrpc.HotelService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=225,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_hotel_details',
    full_name='protobuf.socketrpc.HotelService.get_hotel_details',
    index=0,
    containing_service=None,
    input_type=_HOTEL_REQUEST,
    output_type=_HOTEL,
    options=None,
  ),
])

HotelService = service_reflection.GeneratedServiceType('HotelService', (_service.Service,), dict(
  DESCRIPTOR = _HOTELSERVICE,
  __module__ = 'hotel_tag_pb2'
  ))

HotelService_Stub = service_reflection.GeneratedServiceStubType('HotelService_Stub', (HotelService,), dict(
  DESCRIPTOR = _HOTELSERVICE,
  __module__ = 'hotel_tag_pb2'
  ))


# @@protoc_insertion_point(module_scope)
